print('Hello world')
print("Mary's cosmetics")
print('신씨가 소리질렀다."도둑이야"')
print('신씨가 소리질렀다."\도둑이야"')
print('c:\windows')
print("안녕하세요.\n만나서\t\t반갑습니다")
#, 스페이스바 1개
print("오늘은","일요일")
print('naver;kakao;sk;samsung')
print('naver,kakao,sk,samsung',sep=";")
print('naver,kakao,sk,samsung',sep="/")
print('first');print("second")
print('first second');print("second")
print('first', end=' ');print("second")
print('first');print("second")
print(5/3)